### ISSUE TITLE
Is it possible to use notifyItemMoved?

### ISSUE THREAD

**Issue by Shohrukhbek** [luizgrp/SectionedRecyclerViewAdapter#112]
How about adding `ItemTouchHelperAdapter` interface to my adapter?

```
  @Override
    public void onItemMove(int fromPosition, int toPosition) {
        notifyItemMoved(fromPosition, toPosition);
    }

    @Override
    public void onItemDismiss(int position) {

    }
```

**Comment by yccheok** [comment]
I believe you are following guideline in https://medium.com/@ipaulpro/drag-and-swipe-with-recyclerview-b9456d2b1aaf . Yes. That is a very well written guideline and the provided information is correct.

It is a bit tricky to implement drag/move operation with `SectionedRecyclerViewAdapter`, as you need to deal with multiple `Section`s. You need to perform some modification on the guideline, in order to make it works with `SectionedRecyclerViewAdapter`.

1. I assume your adapter has more than 1 `Section`s. Make all `Section` implements `ItemTouchHelperAdapter`

2. In `SimpleItemTouchHelperCallback`, perform the modification to deal with multiple `ItemTouchHelperAdapter`s. For instance

```
    @Override
    public boolean onMove(RecyclerView recyclerView, RecyclerView.ViewHolder source, RecyclerView.ViewHolder target) {
        if (source.getItemViewType() != target.getItemViewType()) {
            return false;
        }

        final int fromPosition = source.getAdapterPosition();
        final int toPosition = target.getAdapterPosition();
        // Notify the adapter of the move
        for (ItemTouchHelperAdapter mAdapter : mAdapters) {
            if (mAdapter.onItemMove(fromPosition, toPosition)) {
                break;
            }
        }
        return true;
    }
```

3. I assume your `Section A` is not interested on the move operation done on `Section B`. This is what you need to do, in your `Section` code. `if (section != this) {` does the trick.

```
    @Override
    public boolean onItemMove(int fromPosition, int toPosition) {
        SectionedRecyclerViewAdapter sectionedRecyclerViewAdapter = dashboardFragment.getSectionedRecyclerViewAdapter();

        if (fromPosition < 0 || toPosition < 0) {
            return false;
        }

        final int itemCount = sectionedRecyclerViewAdapter.getItemCount();
        if (fromPosition >= itemCount || toPosition >= itemCount) {
            return false;
        }

        Section section = sectionedRecyclerViewAdapter.getSectionForPosition(fromPosition);

        if (section != this) {
            return false;
        }

        dashboardFragment.getDashboardRecyclerViewOnItemClickListener().onItemMove(fromPosition, toPosition);

        // Returning correct boolean is importatnt for optimization purpose.
        return true;
    }
```

4. In `getDashboardRecyclerViewOnItemClickListener().onItemMove` function, you are receiving the absolute adapter fromPosition and absolute adapter toPosition. What you need to do is

- Convert absolute `fromPosition` to `Section` by using `sectionedRecyclerViewAdapter.getSectionForPosition`. Note, `toPostion` should give you same `Section` to. This is because in Paul Burke's `SimpleItemTouchHelperCallback`, it contains the following code.

```
    @Override
    public boolean onMove(RecyclerView recyclerView, RecyclerView.ViewHolder source, RecyclerView.ViewHolder target) {
        if (source.getItemViewType() != target.getItemViewType()) {
            return false;
        }
```

- Convert absolute position to relative position. For instance.

            final NoteSection noteSection = (NoteSection)sectionedRecyclerViewAdapter.getSectionForPosition(fromPosition);

            final List<Note> sectionNotes = noteSection.getNotes();

            final int fromPositionInSection = sectionedRecyclerViewAdapter.getPositionInSection(fromPosition);
            final int toPositionInSection = sectionedRecyclerViewAdapter.getPositionInSection(toPosition);

            final Note from = sectionNotes.get(fromPositionInSection);
            final Note to = sectionNotes.get(toPositionInSection);

- Update your underlying data-structure accordingly.
- Issue `notifyItemMovedInSection`

Note, there's no generalized solution for implementing drag-n-move operation. Hence, it takes some pain and effort :)

If possible, you may consider using `DiffUtil`. My experience is that, using `DiffUtil`, makes my code more generalized, and easier to maintain. I need not worry issuing wrong `notify...` message to adapter. But, again, it also takes some effort to implement `DiffUtil` correct. Please refer to https://github.com/luizgrp/SectionedRecyclerViewAdapter/issues/108#issuecomment-385189455 for more information regarding `DiffUtil`.
