### ISSUE TITLE
How to obtain position the position of the head？

### ISSUE THREAD

**Issue by HotBitmapGG** [luizgrp/SectionedRecyclerViewAdapter#18]
Hi,How can I get the head position location, I need to get the location of the head of each section of the position Then call RecyclerView. SmoothScrollToPosition () to jump to the corresponding position

**Comment by luizgrp** [comment]
Hi, method ```getSectionPosition(tag)``` was added in the library version 1.0.5 in order to get the position of the sector in the adapter. An example using ```smoothScrollToPosition``` was also added [here](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/c6d4ec720d713c126227cc430627451e130018a2/app/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/demo/Example8Fragment.java#L89-L93).
Please let me know if that helps!
