### ISSUE TITLE
Design suggestion based on the following use case

### ISSUE THREAD

**Issue by yccheok** [luizgrp/SectionedRecyclerViewAdapter#193]
Hi,

I would like to know, is `SectionedRecyclerViewAdapter` a good candidate to implement the following case?

![Screenshot_20200422-012340](https://user-images.githubusercontent.com/308276/79895744-f1072100-8439-11ea-8d58-7b8d4718b497.png)

https://youtu.be/CdNOw4jyD00

My initial design thought is that

### Using SectionedRecyclerViewAdapter

1. Every A, B, C, ... is Section A, Section B, Section C
2. Section B will has 1 header, 3 content items (B.1, B.2, B.3)
3. Section A, C, ... will have 1 header, 0 content items.
 
However, such design might be highly inefficient as, you need to dynamically allocate a lot of `Section`, add/ remove `Section` during run-time. Most of the time, the number of Section content item will be 0.

### NOT Using SectionedRecyclerViewAdapter

Another approach I can think of, is treating this `RecyclerView` is only having 1 view type.

A single class data structure will used to hold information A, B, B.1, B.2, B.3, C, ...

During `onBindViewHolder`, we will then slightly adjust the UI outlook, based on whether the item is B or B.1

Do you have any suggestion what are some other better approaches I can use?

Thank you.

**Comment by luizgrp** [comment]
Hi @yccheok, I'm afraid I agree with you that this library wouldn't be the best to build that kind of layout. In order to do that efficiently the library would need to support including items that are not sections.

I would recommend you to try [Groupie](https://github.com/lisawray/groupie). B and E would be of type [ExpandableGroup](https://github.com/lisawray/groupie/blob/c3411d814f18e9b308e3b829b1e8a532f34b6ee2/library/src/main/java/com/xwray/groupie/ExpandableGroup.java) and the others would be of type [Item](https://github.com/lisawray/groupie/blob/c3411d814f18e9b308e3b829b1e8a532f34b6ee2/library/src/main/java/com/xwray/groupie/Item.java).
