### ISSUE TITLE
Refreshing individual items in a section

### ISSUE THREAD

**Issue by ahaverty** [luizgrp/SectionedRecyclerViewAdapter#29]
Is it possible to refresh an individual item in a section rather than reloading all data?

**Comment by luizgrp** [comment]
Hi @ahaverty,

Have a look on the [Animations](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/22e73815e88b47e8a1e9b5890f191d6e5075c07a/app/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/demo/Example8Fragment.java) example in the demo app, there is [code](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/22e73815e88b47e8a1e9b5890f191d6e5075c07a/app/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/demo/Example8Fragment.java#L178) there refreshing individual items in a section.

Let me know if you still have issues.

Cheers

**Comment by ahaverty** [comment]
Thanks @luizgrp 
I've since gone back to using native recycler views with sorted lists doing the updating work form me ([see here for an example](http://stackoverflow.com/a/29807983/2276198)). I don't think this repo could currently support sorted lists like that, as it looks like the category headers are actually adapted list items.
I've gone with this as I'm using Firebase and doing a lot of _complex_ asynchronous realtime updates with lists, and was finding it tedious manually updating the list.

If you think Sorted List could fit in with Sectioned Recycler View Adapter, i'd love to hear your suggestions.

Thanks for a great repo 👍

**Comment by luizgrp** [comment]
Thanks for the update!

Section headers are just items in the RecyclerView but they are not items in your section's list. Thus I see no problem in using SortedList with this adapter, you will just have to adapt the code from the SO link you posted to use the notify methods from this adapter instead of the native adapter (e.g.: `notifyItemRangeInserted` to `notifyItemRangeInsertedInSection`).

Unless there are other issues which I can't see now. Let me know if you give it another try, I would be interested in hear the issues you faced with it.

**Comment by ahaverty** [comment]
Interesting! I'll give that a shot and report back 👌 Thanks for the help
