### ISSUE TITLE
Disable touch on "section"

### ISSUE THREAD

**Issue by jgutierrez11** [luizgrp/SectionedRecyclerViewAdapter#4]
Hello, I was testing this lib and I found out that "section" is clicked like any normal item. How can I prevent "section" from triggering the click event. And how can I add a custom long press event in the section?

Thanks in advanced, great work!

**Comment by luizgrp** [comment]
Hi @jgutierrez11,

You mean the "header" of the section is clicked like any normal item? If so, you can check the first [example](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/master/app/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/demo/Example1Fragment.java), the header is not clickable. You can find the layout for the header [here](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/master/app/src/main/res/layout/section_ex1_header.xml).

In order to add a long press in a view you can use [OnLongClickListener](http://developer.android.com/reference/android/view/View.OnLongClickListener.html), for example, you can use setOnLongClickListener instead of setOnClickListener [here](https://github.com/luizgrp/SectionedRecyclerViewAdapter/blob/master/app/src/main/java/io/github/luizgrp/sectionedrecyclerviewadapter/demo/Example1Fragment.java#L91).

Cheers

**Comment by jgutierrez11** [comment]
Excellent, I just implemented it. And works great.
Another question: How can I make the headers to be Sticky?
Thanks!

**Comment by luizgrp** [comment]
sticky headers is not currently implemented in the library, but it is on my road map :)

**Comment by jgutierrez11** [comment]
Great! Waiting for that feature 👍
