### ISSUE TITLE
Making Section title sticky

### ISSUE THREAD

**Issue by hadiidbouk** [luizgrp/SectionedRecyclerViewAdapter#78]
Is this library support a sticky section title ? and to be replaced with a new arrival  section title

**Comment by ShuichiSyad** [comment]
Yes it can. But you have to do most of the code by yourself. Set it up with your recyclerView and create a "fake TextView" with the same layout as your "header layout". 

Set your recyclerView to get the `.firstVisibleItemPosition()` from `onScrolled` . Next, set your TextView to `.setText()` with data from your header.

**Comment by luizgrp** [comment]
As @ShuichiSyad replied, this library is a custom adapter not a custom recyclerview, in order to implement sticky headers you have to customise the recyclerview yourself or use a library (in conjunction with this one, if the other library doesn't tie you to their custom adapter).

You can also try the answers from this [thread](https://stackoverflow.com/questions/32949971/how-can-i-make-sticky-headers-in-recyclerview-without-external-lib) in stackoverflow, in order to use in conjunction to this library.

**Comment by jeffdgr8** [comment]
For anyone looking for a solution for sticky headers, it was easy to implement using this library: https://github.com/bgogetap/StickyHeaders

I wrote a small class for utilizing together with this library: https://gist.github.com/jeffdgr8/61a4c6432401bf2740cd17cd04f7ee4e

**Comment by itaispector** [comment]
@jeffdgr8 Thanks for sharing your solution, Tough I've tried and it didn't work.

**Comment by iDuuck** [comment]
@itaispector What exactly isn't working? Working flawlessly for me.
