### ISSUE TITLE
How to decorate only child items

### ISSUE THREAD

**Issue by htooaunghlaing** [luizgrp/SectionedRecyclerViewAdapter#97]
### QUESTION TEMPLATE
- [x] I have read over the documentation, checked out the examples and the demo app.
- [x] I have given my issue a non-generic title.
- [x] I understand that if I ask the same question in [stackoverflow](http://www.stackoverflow.com) website I will get answers way faster as more people will try to answer it.
- [x] I understand that if I don't show a minimum effort of what I have tried and where I got stuck the question will be closed and marked as invalid.
- [x] I have read the article [How do I ask a good question?](https://stackoverflow.com/help/how-to-ask)
- [x] I understand that this library is a custom [Adapter](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html) and **NOT** a custom [RecyclerView](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.html). I understand the difference between them and what is possible to be done in an Adapter but not in a RecyclerView.

###### Expected behaviour
I want to decorate child items with EqualSpacingItemDecoration(https://gist.github.com/alexfu/f7b8278009f3119f523a) 

### Demo Project
https://github.com/htooaunghlaing/Grid-Section-Recycler

###### Actual behaviour
In really, header row was assume as one cell, so, the 3rd item was always align to right.
Pelase see the attachment image (https://imgur.com/a/vAtiD)

###### MCVE
```java
 @Override
 public RecyclerView.ViewHolder getItemViewHolder(View view) {
            ItemViewHolder holder =  new ItemViewHolder(view);
            view.getLayoutParams().height = (int) (Utality.getDeviceWidth(getContext()) / 3 * 1.9f); //3 is Span Count & 1.9f is image ratio
            return holder;
        }
```

#### Checked in decoration class,
```java
case GRID:
                if (layoutManager instanceof GridLayoutManager) {
                    GridLayoutManager gridLayoutManager = (GridLayoutManager) layoutManager;
                    int cols = gridLayoutManager.getSpanCount();
                    int rows = itemCount / cols;
                    int viewType = parent.getAdapter().getItemViewType(position);
                    if(viewType != SectionedRecyclerViewAdapter.VIEW_TYPE_HEADER){
                        outRect.left = spacing;
                        outRect.right = position % cols == cols - 1 ? spacing : 0;
                        outRect.top = spacing;
                        outRect.bottom = position / cols == rows - 1 ? spacing : 0;
                    }
                }
```

#### Span Size LookUp
```java
GridLayoutManager glm = new GridLayoutManager(getContext(), 3);
        glm.setSpanSizeLookup(new GridLayoutManager.SpanSizeLookup() {
            @Override
            public int getSpanSize(int position) {
                switch(sectionAdapter.getSectionItemViewType(position)) {
                    case SectionedRecyclerViewAdapter.VIEW_TYPE_HEADER:
                        return 3;
                    default:
                        return 1;
                }
            }
        });
```
Please don't hesitate and feel free to talk me if I make something wrong.

**Comment by luizgrp** [comment]
Hi @htooaunghlaing,

Do you think there is an **issue** with this library that is not allowing you to use ItemDecoration properly? Or you have a **question** how to use that EqualSpacingItemDecoration code with this library? 
If it's a question please edit your template with the question template.
If it's an issue please edit your template and clarify:

###### Expected behaviour
What's the expected behaviour? You want to see equal spacing between the items of the section?

###### Actual behaviour
Thanks for the image, but please clarify what is the actual behaviour, the item on the very right has no space on the right?

###### MCVE
Please provide a simpler ItemDecoration, setting a fixed amount of spacing and simple layouts.

**Comment by htooaunghlaing** [comment]
@luizgrp , I have created a demo project for it.please check it out and let me know if I missed somethings else. Thanks you .

https://github.com/htooaunghlaing/Grid-Section-Recycler

**Comment by htooaunghlaing** [comment]
@luizgrp , I have updated my issue and added codes and example and Iet me know any response from you.

**Comment by luizgrp** [comment]
Could you please clarify the expected behaviour and the current behaviour?
You want to have equal spacing between the content items and the items from the 3rd column don't have spacing on the right? Is that what you mean?

Your example still has too much code, is not minimal, I can't answer for that code from that gist.
Try to create your own RecyclerView.ItemDecoration, with minimal code.
Try to find out the line of code where the issue is so I can try to help you.

If you need quicker help please use stackoverflow.com
